# Generated by Django 3.1.5 on 2021-01-28 07:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Timer', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='memoCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='memoTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='totalTime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
