# Generated by Django 3.1.5 on 2021-01-28 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timer', '0006_auto_20210128_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
